#FROM stg.nvcr.io/nvidia/cuda:10.0-devel-ubuntu16.04
FROM stg.nvcr.io/nvidia/cuda:9.2-devel-ubuntu16.04
#FROM nvidia/cuda:10.0-devel-ubuntu18.04

# install prequesites for nvSUPRA
RUN apt-get update && apt-get install -y cmake libtbb-dev libopenigtlink-dev libcpprest-dev libboost-all-dev less

# build nvSUPRA
# COPY . /nvSupra
COPY build /nvSupra/build
