#FROM stg.nvcr.io/nvidia/cuda:10.0-devel-ubuntu16.04
#FROM stg.nvcr.io/nvidia/cuda:9.2-devel-ubuntu16.04
FROM test/cudaxavier

# install prequesites for nvSUPRA
RUN apt-get update && apt-get install -y cmake libtbb-dev libopenigtlink-dev libcpprest-dev libboost-all-dev less
COPY dockerfiles/dockerBuildAuxilliary/libcpprest2.10_cmake_aarch64/cpprestsdk-config.cmake /usr/lib/aarch64-linux-gnu/cmake/
COPY dockerfiles/dockerBuildAuxilliary/libcpprest2.10_cmake_aarch64/cpprestsdk-targets.cmake /usr/lib/aarch64-linux-gnu/cmake/
COPY dockerfiles/dockerBuildAuxilliary/libcpprest2.10_cmake_aarch64/cpprestsdk-targets-none.cmake /usr/lib/aarch64-linux-gnu/cmake/

# build nvSUPRA
COPY . /nvSupra
ENTRYPOINT ["/bin/bash", "-c", "cd /nvSupra && mkdir -p build/build && cd build/build && CMAKE_PREFIX_PATH=/usr/lib/aarch64-linux-gnu/cmake:$CMAKE_PREFIX_PATH cmake ../.. -DCMAKE_BUILD_TYPE=RELWITHDEBINFO -DSUPRA_DEVICE_IGTL_OUTPUT=ON -DSUPRA_INTERFACE_REST=ON && make -j5"]
